{"uid":"1561815528981bde","name":"test_getsAddressList[result0]","fullName":"testcases.test_address#test_getsAddressList","historyId":"792ca8eb8ffd296dc312288cee8623be","time":{"start":1706176287677,"stop":1706176287683,"duration":6},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":4,"retriesStatusChange":true,"beforeStages":[{"name":"getToken","time":{"start":1706176287669,"stop":1706176287677,"duration":8},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0}],"afterStages":[{"name":"getToken::0","time":{"start":1706176287964,"stop":1706176287964,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0}],"labels":[{"name":"parentSuite","value":"testcases"},{"name":"suite","value":"test_address"},{"name":"host","value":"DESKTOP-061EAN7"},{"name":"thread","value":"16640-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"testcases.test_address"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"result","value":"('001', 'succ-getAddressList', 'address', '192.168.0.105:3000', '/api/user/address', 'get', '1', 'null', '{\\r\\n  \"errno\": 0,\\r\\n  \"data\": [],\\r\\n  \"message\": \"获取全部地址成功\"\\r\\n}\\r\\n', '{\\r\\n  \"errno\": 0,\\r\\n  \"data\": [],\\r\\n  \"message\": \"获取全部地址成功\"\\r\\n}\\r\\n', 'miss', 'ignore')"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"b3ee8f0eec85491b","status":"passed","time":{"start":1706176012461,"stop":1706176012477,"duration":16}},{"uid":"6ebed51a52a9b14b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.0.105', port=3000): Max retries exceeded with url: /api/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000235656B9BA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1706024559446,"stop":1706024559446,"duration":0}},{"uid":"4a630288ecb6b240","status":"passed","time":{"start":1705648175265,"stop":1705648175287,"duration":22}},{"uid":"b0de72f0fe71afe3","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015309399C30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1705648138299,"stop":1705648138299,"duration":0}}],"categories":[],"tags":[]},"source":"1561815528981bde.json","parameterValues":["('001', 'succ-getAddressList', 'address', '192.168.0.105:3000', '/api/user/address', 'get', '1', 'null', '{\\r\\n  \"errno\": 0,\\r\\n  \"data\": [],\\r\\n  \"message\": \"获取全部地址成功\"\\r\\n}\\r\\n', '{\\r\\n  \"errno\": 0,\\r\\n  \"data\": [],\\r\\n  \"message\": \"获取全部地址成功\"\\r\\n}\\r\\n', 'miss', 'ignore')"]}