{"uid":"6328afffd0309615","name":"test_order_submit[result1]","fullName":"testcases.test_order#test_order_submit","historyId":"5dd2ad784c0ec9a9715bdafce56c6124","time":{"start":1706176287772,"stop":1706176287780,"duration":8},"status":"failed","statusMessage":"AssertionError: assert 30001 == 0","statusTrace":"result = ('002', 'fail_order_commit', 'order', '192.168.0.105:3000', '/api/order', 'post', ...)\ngetToken = <RequestsCookieJar[Cookie(version=0, name='koa.sid', value='DLDZEOfXlVrEabSDWbb1YAapHPWgJ6cy', port=None, port_specifi...ure=False, expires=1706262687, discard=False, comment=None, comment_url=None, rest={'httponly': None}, rfc2109=False)]>\n\n    @pytest.mark.parametrize(\"result\", data_order_submit())\n    def test_order_submit(result,getToken):\n        cookie= getToken\n        request_prefix = result[3]\n        request_url = result[4]\n        request_type = result[5]\n        data = result[7]\n        expect_result = result[8]\n        url = 'http://' + request_prefix + request_url\n        dataDict = json.loads(data)\n        expect_resultDict = json.loads(expect_result)\n        res = Request.send_request(url, method=request_type, json=dataDict, cookies=cookie).json()\n>       assert  expect_resultDict[\"errno\"]==res[\"errno\"]\nE       assert 30001 == 0\n\ntestcases\\test_order.py:38: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":4,"retriesStatusChange":true,"beforeStages":[{"name":"getToken","time":{"start":1706176287669,"stop":1706176287677,"duration":8},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0}],"afterStages":[{"name":"getToken::0","time":{"start":1706176287964,"stop":1706176287964,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0}],"labels":[{"name":"parentSuite","value":"testcases"},{"name":"suite","value":"test_order"},{"name":"host","value":"DESKTOP-061EAN7"},{"name":"thread","value":"16640-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"testcases.test_order"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"result","value":"('002', 'fail_order_commit', 'order', '192.168.0.105:3000', '/api/order', 'post', '1', 'null', '{\"errno\":30001, \"message\":\"创建订单出错\"}', '{\"errno\":30001, \"message\":\"创建订单出错\"}', 'pass', 'ignore')"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"9a2a474633554637","status":"failed","statusDetails":"AssertionError: assert 30001 == 0","time":{"start":1706176012611,"stop":1706176012619,"duration":8}},{"uid":"62b801e2b9af5ae6","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.0.105', port=3000): Max retries exceeded with url: /api/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000235656B9BA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1706024562842,"stop":1706024562842,"duration":0}},{"uid":"44b23c4ed276fd3","status":"failed","statusDetails":"AssertionError: assert 30001 == 0","time":{"start":1705648175448,"stop":1705648175462,"duration":14}},{"uid":"829f1fa11d3b9d89","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015309399C30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1705648143809,"stop":1705648143809,"duration":0}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"6328afffd0309615.json","parameterValues":["('002', 'fail_order_commit', 'order', '192.168.0.105:3000', '/api/order', 'post', '1', 'null', '{\"errno\":30001, \"message\":\"创建订单出错\"}', '{\"errno\":30001, \"message\":\"创建订单出错\"}', 'pass', 'ignore')"]}