{"uid":"dde8b1bbd7520535","name":"test_order_getall[result0]","fullName":"testcases.test_order#test_order_getall","historyId":"6a88d5ad1d7de6f85f78d77a9eb85c7f","time":{"start":1706176287896,"stop":1706176287917,"duration":21},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":4,"retriesStatusChange":true,"beforeStages":[{"name":"getToken","time":{"start":1706176287669,"stop":1706176287677,"duration":8},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0}],"afterStages":[{"name":"getToken::0","time":{"start":1706176287964,"stop":1706176287964,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0}],"labels":[{"name":"parentSuite","value":"testcases"},{"name":"suite","value":"test_order"},{"name":"host","value":"DESKTOP-061EAN7"},{"name":"thread","value":"16640-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"testcases.test_order"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"result","value":"('003', 'succ_order_getAll', 'order', '192.168.0.105:3000', '/api/order', 'get', '1', 'null', '{\"errno\":0,\"data\":[]}', '{\"errno\":0,\"data\":[]}', 'pass', 'ignore')"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"f41f8f3868551db9","status":"broken","statusDetails":"KeyError: 'message'","time":{"start":1706176012732,"stop":1706176012773,"duration":41}},{"uid":"718f6be754103361","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.0.105', port=3000): Max retries exceeded with url: /api/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000235656B9BA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1706024563001,"stop":1706024563001,"duration":0}},{"uid":"ebd5a39f8564059c","status":"broken","statusDetails":"KeyError: 'message'","time":{"start":1705648175590,"stop":1705648175627,"duration":37}},{"uid":"b8627919718d53a8","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015309399C30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1705648144000,"stop":1705648144000,"duration":0}}],"categories":[],"tags":[]},"source":"dde8b1bbd7520535.json","parameterValues":["('003', 'succ_order_getAll', 'order', '192.168.0.105:3000', '/api/order', 'get', '1', 'null', '{\"errno\":0,\"data\":[]}', '{\"errno\":0,\"data\":[]}', 'pass', 'ignore')"]}